export const PUSHER_EVENTS = {
  RECEIVE_CONTACT: 'receive_contact',
  CANCEL_CONTACT: 'cancel_contact',
  DELETE_CONTACT: 'delete_contact',
  CONFIRM_CONTACT: 'confirm_contact',
  UNFRIEND_CONTACT: 'unfriend_contact',
  GET_MESSAGE: 'get_message',
  CONNECT_CONTACT: 'connect_contact',
  DISCONNECT_CONTACT: 'disconnect_contact',
  READ_MESSAGES: 'read_messages',
  RECEIVE_CALL: 'receive_call',
  STOP_CALL: 'stop_call',
  START_CALL: 'start_call',
  END_CALL: 'end_call',
};
